#if !canImport(ObjectiveC)
import XCTest

extension VaporMonitoringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VaporMonitoringTests = [
        ("testVaporMonitoring", testVaporMonitoring),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(VaporMonitoringTests.__allTests__VaporMonitoringTests),
    ]
}
#endif
